version: '3.8'

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=DataWarehouse
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  core:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/DataWarehouse?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
    volumes:
      - ~/.m2:/root/.m2
      - .:/app

